# These are supported funding model platforms

github: [REChain-Network-Solutions, rechain-dao-team]
patreon: rechaindao
open_collective: rechain-dao
ko_fi: rechaindao
tidelift: # Replace with a single Tidelift package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: rechaindao
issuehunt: rechain-dao
otechie: rechaindao
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: ['https://rechain-dao.com/donate', 'https://gitcoin.co/grants/rechain-dao', 'https://etherscan.io/donate/rechaindao']
