apiVersion: v1
kind: ConfigMap
metadata:
  name: rechain-dao-config
  namespace: rechain-dao
data:
  NODE_ENV: "production"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "rechain_dao"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  LOG_LEVEL: "info"
  CORS_ORIGIN: "https://rechain-dao.com"
  PROMETHEUS_ENDPOINT: "http://prometheus-service:9090"
  GRAFANA_ENDPOINT: "http://grafana-service:3000"
